name: deploy
run-name: deploy the app
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - "main"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - run: echo DEV dpeloy
  deploy-qa:
    runs-on: ubuntu-latest
    environment: "qa"
    steps:
      - run: echo QA dpeloy
