name: deploy
run-name: deploy the app
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - "main"
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy run!
