name: deploy
run-name: deploy the app
on:
  workflow_run:
    workflows: ["docker-build-and-push"]
    types:
      - completed
    branches:
      - "main"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: "dev"
    steps:
      - run: echo DEV dpeloy
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.9
        with:
          app-name: my-test-web-app-12345.azurewebsites.net
          publish-profile: ${{ secrets.WEB_APP_PUBLISH_PROFILE }}
          slot-name: dev
   
  deploy-qa:
    runs-on: ubuntu-latest
    environment: "qa"
    steps:
      - run: echo QA dpeloy
