name: docker_build_push
on:
  push:
    branches:
      - main
      
env:
  IMAGE_NAME: my-web-api
  IMAGE_REGISTRY: myrepo12345.azurecr.io

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: production
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: 'Docker Login'
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - name: Build the frontend image and push it to ACR
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:v1.${{ github.run_number }}, 
        file: src/WebApi/Dockerfile
